name: flutter_artist_dio
description: A powerful HTTP networking wrapper built on top of Dio. Features standalone automated multi-format backend error parsing and comprehensive response logging telemetry.
version: 0.9.1
resolution: workspace
homepage: https://o7planning.github.io

environment:
  sdk: ^3.6.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  tabbed_view: ^3.1.0
  animated_tree_view: ^2.3.0
  dio: ^5.9.2
  fresh_dio: ^0.6.0
  flutter_advanced_switch: ^3.2.0
  hovering: ^1.0.4

  flutter_artist_core: ^0.9.1
  flutter_artist_commons_ui: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - statics-rs/
    - statics-rs/array.gif
    - statics-rs/object.gif